### ISSUE TITLE
Moonbound event screens

### ISSUE THREAD

**Issue by kellan-simiotics** [moonstream-to/frontend#122]
* Title screen
* Claim Initiate screen (possibly the same screen as profile)
* Player profile screen
  * View Initiate progression
  * View Initiate items
* Game screen (garden of forking paths enhancements and customizations)

@s-c-orr can you provide some details here?

**Comment by s-c-orr** [comment]
Player profile screen:

* there are nine stages of the game and six sections of the labyrinth
  * for players still in game, show stage and section
  * for eliminated players, show how far they got
* players earn an item in each section of the labyrinth. there are six items
  * show the items on the Initiate image on the profile screen (we have art of the character with the items equipped, rather than separate images of each item)
   * list the items the player has earned


Game screen/Garden:

* a place to display the session lore in stage one (maybe a separate lore box similar to the stage lore box)
* event-specific colors for fonts, text boxes, maybe background

**Comment by s-c-orr** [comment]
Here is the flow for connecting to the game:

* A player goes to the title screen (moonbound.moonstream.to) for the first time. The title screen shows the game title and logo and has "Help" and "Instructions" links. The title screen has a "Play" button.
* The player clicks "Play" and is prompted to connect their wallet.
* The player is taken to the claim screen. There they see different options depending on whether or not their wallet address is on the whitelist.
  * The player gets a message welcoming them to Moonbound and giving short description of the game.
  * If on the whitelist: The player sees the claim button ("Enter the Labyrinth") with directions to click it to claim an Initiate NFT and begin the game.
  * If not on the whitelist: The player sees a message saying sorry, you aren't on the white list. Click here to request access to the whitelist. There is a button that they can click to ask to be allowed to play. If their request is granted, they (are somehow notified) and are taken to the screen with the claim button.
* After successfully claiming an NFT, the player is taken to the profile/game screen. They are greeted with a box that pops up congratulating them on successfully claiming the NFT and giving some instructions about how to play the game. 
* The player can close the box and interact with the profile/game screen to view their characters, read the lore, and choose paths.
